# Generated by Django 5.1.7 on 2025-04-22 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoSanguineo',
            fields=[
                ('id_sangre', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sangre', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'grupo_sanguineo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('id_sangre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.gruposanguineo')),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
