# Generated by Django 5.1.7 on 2025-04-25 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_gruposanguineo_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol'),
        ),
    ]
