# Generated by Django 5.1.7 on 2025-04-25 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_especialidad_centromedico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id_doctor', models.AutoField(primary_key=True, serialize=False)),
                ('numero_licencia', models.CharField(max_length=100, unique=True)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorCentro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aceptado_por_centromedico', models.BooleanField(default=False)),
                ('id_centromedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.centromedico')),
                ('id_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='EspecialidadDoctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.doctor')),
                ('id_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.especialidad')),
            ],
        ),
    ]
