# Generated by Django 5.1.7 on 2025-05-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_doctor_doctorcentro_especialidaddoctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorcentro',
            old_name='id',
            new_name='id_doctorcentro',
        ),
    ]
