# Generated by Django 5.1.7 on 2025-05-08 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_rename_id_doctorcentro_id_doctorcentro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('medicamento', 'Medicamento'), ('alimento', 'Alimento'), ('ambiental', 'Ambiental'), ('otro', 'Otro')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PacienteAlergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravedad', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('severa', 'Severa')], max_length=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('alergia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.alergia')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alergias', to='usuarios.paciente')),
            ],
            options={
                'unique_together': {('paciente', 'alergia')},
            },
        ),
    ]
