# Generated by Django 5.1.7 on 2025-05-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_vacuna_vacunapaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacuna',
            name='max_dosis',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
