# Generated by Django 5.1.7 on 2025-05-11 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_vacuna_max_dosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnfermedadPersistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PacienteEnfermedadPersistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_diagnostico', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.enfermedadpersistente')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermedades_persistentes', to='usuarios.paciente')),
            ],
            options={
                'unique_together': {('paciente', 'enfermedad')},
            },
        ),
    ]
