# Generated by Django 5.1.7 on 2025-05-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_enfermedadpersistente_pacienteenfermedadpersistente'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermedadpersistente',
            name='tipo',
            field=models.CharField(choices=[('endocrina', 'Endocrina'), ('cardiovascular', 'Cardiovascular'), ('respiratoria', 'Respiratoria'), ('neurologica', 'Neurológica'), ('psiquiatrica', 'Psiquiátrica'), ('gastrointestinal', 'Gastrointestinal'), ('reumatologica', 'Reumatológica'), ('renal', 'Renal'), ('hematologica', 'Hematológica'), ('infecciosa', 'Infecciosa')], default='endocrina', max_length=20),
        ),
        migrations.AlterField(
            model_name='enfermedadpersistente',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
