# Generated by Django 5.1.7 on 2025-05-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_enfermedadpersistente_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='imagenes_prueba/')),
            ],
        ),
    ]
