# Generated by Django 5.1.7 on 2025-05-14 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_usuario_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoCronico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PacienteMedicamentoCronico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('dosis', models.CharField(blank=True, max_length=50)),
                ('frecuencia', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('doctor_aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.doctor')),
                ('id_medicamento_cronico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medicamentocronico')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.paciente')),
            ],
        ),
    ]
