# Generated by Django 5.1.7 on 2025-05-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_medicamentocronico_pacientemedicamentocronico'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEscaneado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='pdfs/')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
