# Generated by Django 5.1.7 on 2025-05-15 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_documentoescaneado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientealergia',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pacientealergia',
            name='doctor_aprobador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.doctor'),
        ),
        migrations.AddField(
            model_name='pacienteenfermedadpersistente',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pacienteenfermedadpersistente',
            name='doctor_aprobador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.doctor'),
        ),
        migrations.AddField(
            model_name='vacunapaciente',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacunapaciente',
            name='doctor_aprobador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.doctor'),
        ),
    ]
