# Generated by Django 5.1.7 on 2025-05-15 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_pacientealergia_aprobado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_examen', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_realizacion', models.DateField()),
                ('archivo', models.FileField(upload_to='examenes/{nombre_examen}/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_laboratorio', to='usuarios.paciente')),
            ],
        ),
    ]
