# Generated by Django 5.1.7 on 2025-05-15 17:40

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_examenlaboratorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='archivo',
            field=models.FileField(upload_to=usuarios.models.ruta_archivo_examen),
        ),
    ]
