# Generated by Django 5.1.7 on 2025-05-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_alter_examenlaboratorio_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenlaboratorio',
            name='categoria',
            field=models.CharField(choices=[('hematologia', 'Hematología'), ('bioquimica', 'Bioquímica'), ('orina_y_heces', 'Orina y Heces'), ('inmunologia', 'Inmunología'), ('espirometria', 'Espirometría'), ('prueba_esfuerzo', 'Prueba de Esfuerzo'), ('electrocardiograma', 'Electrocardiograma'), ('ecocardiograma', 'Ecocardiograma'), ('holter', 'Holter'), ('encefalograma', 'Encefalograma'), ('potenciales_evocados', 'Potenciales Evocados'), ('interconsultas', 'Interconsultas'), ('resumenes_clinicos', 'Resúmenes Clínicos'), ('referencias', 'Referencias'), ('otros', 'Otros'), ('sin_categoria', 'Sin categoría')], default='hematologia', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examenlaboratorio',
            name='tipo',
            field=models.CharField(choices=[('laboratorio', 'Laboratorio'), ('pruebas_funcionales', 'Pruebas Funcionales'), ('cardiologia', 'Cardiología'), ('neurologia', 'Neurología'), ('informes_medicos', 'Informes Médicos'), ('otros_documentos', 'Otros Documentos')], default='otros_documentos', max_length=50),
            preserve_default=False,
        ),
    ]
