# Generated by Django 5.1.7 on 2025-05-18 02:51

import django.db.models.deletion
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_examenlaboratorio_categoria_examenlaboratorio_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenLabImagenologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('nombre_examen', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_realizacion', models.DateField()),
                ('archivo', models.FileField(upload_to=usuarios.models.ruta_archivo_imagenologia)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_imagenologia', to='usuarios.paciente')),
            ],
        ),
    ]
