# Generated by Django 5.1.7 on 2025-05-18 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_examenlabimagenologia'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField()),
                ('dosis', models.PositiveIntegerField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('doctor_aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='usuarios.paciente')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.vacuna')),
            ],
        ),
        migrations.DeleteModel(
            name='VacunaPaciente',
        ),
    ]
