# Generated by Django 5.1.7 on 2025-05-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_tratamientoactual_seguimientotratamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('principio_activo', models.CharField(max_length=100)),
                ('presentacion', models.CharField(max_length=100)),
                ('concentracion', models.CharField(max_length=100)),
                ('via_administracion', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
