# Generated by Django 5.1.7 on 2025-05-20 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_medicamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamientoactual',
            name='nombre',
        ),
        migrations.AddField(
            model_name='tratamientoactual',
            name='medicamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.medicamento'),
            preserve_default=False,
        ),
    ]
