# Generated by Django 5.1.7 on 2025-05-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_remove_tratamientoactual_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamientoactual',
            name='frecuencia',
            field=models.TextField(blank=True),
        ),
    ]
