# Generated by Django 5.1.7 on 2025-05-20 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0030_tratamientoactual_frecuencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientotratamiento',
            name='autor',
        ),
        migrations.AddField(
            model_name='seguimientotratamiento',
            name='rol',
            field=models.CharField(blank=True, choices=[('paciente', 'Paciente'), ('doctor', 'Doctor')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='seguimientotratamiento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
