# Generated by Django 5.1.7 on 2025-05-20 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0031_remove_seguimientotratamiento_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientotratamiento',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='seguimientotratamiento',
            name='usuario',
        ),
        migrations.AddField(
            model_name='seguimientotratamiento',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.doctor'),
        ),
    ]
