# Generated by Django 5.1.7 on 2025-05-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0032_remove_seguimientotratamiento_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientotratamiento',
            name='rol',
            field=models.CharField(blank=True, choices=[('paciente', 'Paciente'), ('doctor', 'Doctor')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
