# Generated by Django 5.1.7 on 2025-06-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0035_doctorpaciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='archivo',
            field=models.URLField(),
        ),
    ]
