# Generated by Django 5.1.7 on 2025-06-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0036_alter_examenlaboratorio_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='archivo',
            field=models.URLField(max_length=500),
        ),
    ]
