# Generated by Django 5.1.7 on 2025-06-05 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0037_alter_examenlaboratorio_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('peso', models.FloatField(blank=True, help_text='Peso en kg', null=True)),
                ('altura', models.FloatField(blank=True, help_text='Talla en metros', null=True)),
                ('presion_sistolica', models.IntegerField(blank=True, null=True)),
                ('presion_diastolica', models.IntegerField(blank=True, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, help_text='lpm', null=True)),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, help_text='rpm', null=True)),
                ('temperatura', models.FloatField(blank=True, help_text='°C', null=True)),
                ('spo2', models.IntegerField(blank=True, help_text='Saturación de oxígeno %', null=True)),
                ('glucosa', models.IntegerField(blank=True, help_text='mg/dL', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Comentario opcional del médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='usuarios.paciente')),
            ],
        ),
    ]
