# Generated by Django 5.1.7 on 2025-06-07 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0038_signosvitales'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenlaboratorio',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_subidos', to='usuarios.doctor'),
        ),
    ]
