# Generated by Django 5.1.7 on 2025-06-08 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0039_examenlaboratorio_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenlabimagenologia',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenologia_subidos', to='usuarios.doctor'),
        ),
    ]
