# Generated by Django 5.1.7 on 2025-06-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0040_examenlabimagenologia_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenlabimagenologia',
            name='archivo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
