# Generated by Django 5.1.7 on 2025-06-14 03:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0042_alter_paciente_id_sangre_alter_paciente_id_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
