# Generated by Django 5.1.7 on 2025-06-14 03:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0043_paciente_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
