# Generated by Django 5.1.7 on 2025-06-22 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0044_alter_paciente_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='usuarios.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='usuarios.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signos_vitales', to='usuarios.consulta'),
        ),
        migrations.AddField(
            model_name='tratamientoactual',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamientos', to='usuarios.consulta'),
        ),
        migrations.CreateModel(
            name='DiagnosticoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('es_enfermedad_preexistente', models.BooleanField(default=False)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='usuarios.consulta')),
            ],
        ),
    ]
