# Generated by Django 5.1.7 on 2025-06-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0045_consulta_signosvitales_consulta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nacionalidad',
            field=models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero')], default='V', max_length=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=1),
        ),
    ]
