# Generated by Django 5.1.7 on 2025-06-25 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0046_usuario_nacionalidad_usuario_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenFuncional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.TextField()),
                ('piel', models.TextField()),
                ('cabeza', models.TextField()),
                ('oidos', models.TextField()),
                ('nariz', models.TextField()),
                ('boca', models.TextField()),
                ('respiratorio', models.TextField()),
                ('osteomuscular', models.TextField()),
                ('cardiovascular', models.TextField()),
                ('gastrointestinal', models.TextField()),
                ('genitourinario', models.TextField()),
                ('nervioso', models.TextField()),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen_funcional', to='usuarios.consulta')),
            ],
        ),
    ]
