# Generated by Django 5.1.7 on 2025-06-28 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0047_examenfuncional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.TextField(blank=True, null=True)),
                ('piel', models.TextField(blank=True, null=True)),
                ('uñas', models.TextField(blank=True, null=True)),
                ('cabeza', models.TextField(blank=True, null=True)),
                ('ojos', models.TextField(blank=True, null=True)),
                ('nariz', models.TextField(blank=True, null=True)),
                ('oidos', models.TextField(blank=True, null=True)),
                ('boca_faringe', models.TextField(blank=True, null=True)),
                ('cuello', models.TextField(blank=True, null=True)),
                ('ganglios', models.TextField(blank=True, null=True)),
                ('torax', models.TextField(blank=True, null=True)),
                ('pulmones', models.TextField(blank=True, null=True)),
                ('corazon', models.TextField(blank=True, null=True)),
                ('abdomen', models.TextField(blank=True, null=True)),
                ('genitales', models.TextField(blank=True, null=True)),
                ('recto', models.TextField(blank=True, null=True)),
                ('osteomuscular', models.TextField(blank=True, null=True)),
                ('neurologico_psiquico', models.TextField(blank=True, null=True)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen_fisico', to='usuarios.consulta')),
            ],
        ),
    ]
