# Generated by Django 5.1.7 on 2025-06-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0048_examenfisico'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='sintomas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
