# Generated by Django 5.1.7 on 2025-06-29 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0049_consulta_sintomas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticoconsulta',
            name='es_enfermedad_preexistente',
        ),
        migrations.AlterField(
            model_name='diagnosticoconsulta',
            name='consulta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico', to='usuarios.consulta'),
        ),
    ]
