# Generated by Django 5.1.7 on 2025-07-01 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0050_remove_diagnosticoconsulta_es_enfermedad_preexistente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnfermedadComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('respiratoria', 'Respiratoria'), ('viral', 'Viral'), ('bacterial', 'Bacteriana'), ('digestiva', 'Digestiva'), ('dermatologica', 'Dermatológica'), ('otros', 'Otros')], default='otros', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PacienteEnfermedadComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_diagnostico', models.DateField(auto_now_add=True)),
                ('fecha_recuperacion', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('doctor_aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.doctor')),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.enfermedadcomun')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermedades_comunes', to='usuarios.paciente')),
            ],
            options={
                'ordering': ['-fecha_diagnostico'],
            },
        ),
    ]
